export const exapmleData = {
  client: 'Hello',
  tranId: '6739f6fb-988d-4dc8-ac38-1bdea666e26f',
  tranSeq: 'Hello',
  tranDatetime: 'Hello',
  passageCode: 'Hello',
  hqNum: 'Hello',
  plazaNum: 'Hello',
  laneNum: 'Hello',
  agentCode: 'Hello',
  entryHqNum: 'Hello',
  entryPlazaNum: 'Hello',
  entryLaneNum: 'Hello',
  vehicleClass: 'Hello',
  paymentType: 'Hello',
  fee: 1.4,
  balance: 1.4,
  refPan: 'Hello',
  refTag: 'Hello',
  timeStamp: 'Hello',
  vehicles: [
    {
      cameraCode: 'Hello',
      cameraNo: 'Hello',
      plate1: 'Hello',
      plate2: 'Hello',
      percentageCharacter: 1.4,
      percentageProvince: 1.4,
      plateNo1: 'Hello',
      plateNo2: 'Hello',
      plateNo3: 'Hello',
      plateNo4: 'Hello',
      plateNo5: 'Hello',
      plateColor: 'Hello',
      province: 'Hello',
      country: 'Hello',
      vehicleType: 'Hello',
      vehicleWheel: 'Hello',
      vehicleBrand: 'Hello',
      vehicleColor: ['Hello'],
      platePicName: 'Hello',
      platePicData: 'Hello',
      bodyPicName: 'Hello',
      bodyPicData: 'Hello',
      overallPicName: 'Hello',
      overallPicData: 'Hello',
      crossLane: {
        platePicName: 'Hello',
        platePicData: 'Hello',
        bodyPicName: 'Hello',
        bodyPicData: 'Hello',
        plate1: 'Hello',
        plate2: 'Hello',
        province: 'Hello',
      },
      timeStamp: 'Hello',
    },
  ],
};
